# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cebaa9a888343fb04a8441a0df5b2714fa6422e5e00d0ad04755e943dd7583d197e4389cdcbb93799f202ddc3fa9a667b27a781237ddfd540e2199d62d7f615f

test:
  secret_key_base: 71d5ab69443d528d314448514b1a3fb8a62d3435d683321a6b7fa5c7c3187b91bab5a197cefa206e28c1355e19fbe22f9663b0ed9f192b6e274a88c9d0badb04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
